# Generated by Django 5.0.4 on 2024-05-19 18:33

import QLKS.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DichVu',
            fields=[
                ('MaDichVu', models.AutoField(primary_key=True, serialize=False)),
                ('TenDichVu', QLKS.models.NVarCharField(max_length=100)),
                ('Gia', models.FloatField()),
                ('MoTa', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DonDatPhong',
            fields=[
                ('MaDonDatPhong', models.AutoField(primary_key=True, serialize=False)),
                ('NgayNhanPhong', models.DateTimeField(default=datetime.datetime(2024, 5, 20, 1, 33, 47, 707264))),
                ('NgayTraPhong', models.DateTimeField()),
                ('TongTienPhong', models.FloatField(default=0)),
                ('TongTienDichVu', models.FloatField(default=0)),
                ('TinhTrang', QLKS.models.NVarCharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('MaHoaDon', models.AutoField(primary_key=True, serialize=False)),
                ('NgayXuat', models.DateTimeField(default=datetime.datetime(2024, 5, 20, 1, 33, 47, 706472))),
                ('TongTien', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('MaKhachHang', models.AutoField(primary_key=True, serialize=False)),
                ('TenKhachHang', QLKS.models.NVarCharField(max_length=100)),
                ('DiaChi', models.TextField()),
                ('SDT', QLKS.models.NVarCharField(max_length=20)),
                ('Email', QLKS.models.NVarCharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoaiPhong',
            fields=[
                ('MaLoai', models.AutoField(primary_key=True, serialize=False)),
                ('TenLoai', QLKS.models.NVarCharField(max_length=50)),
                ('SucChua', models.IntegerField()),
                ('GiaMotNgay', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('MaNhanVien', models.AutoField(primary_key=True, serialize=False)),
                ('HoTen', QLKS.models.NVarCharField(max_length=100)),
                ('ChucVu', QLKS.models.NVarCharField(max_length=50)),
                ('SDT', QLKS.models.NVarCharField(max_length=20)),
                ('Email', QLKS.models.NVarCharField(max_length=100, null=True)),
                ('NgayVaoLam', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='DonDatDichVu',
            fields=[
                ('MaDonDatDichVu', models.AutoField(primary_key=True, serialize=False)),
                ('SoLuong', models.IntegerField(default=1)),
                ('TongTien', models.FloatField(default=0)),
                ('NgayDat', models.DateTimeField(default=datetime.datetime(2024, 5, 20, 1, 33, 47, 707861))),
                ('MaDichVu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_DonDatDichVu_DichVu', to='QLKS.dichvu')),
                ('MaDonDatPhong', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_DonDatDichVu_DonDatPhong', to='QLKS.dondatphong')),
            ],
        ),
        migrations.AddField(
            model_name='dondatphong',
            name='MaHoaDon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_DonDatPhong_HoaDon', to='QLKS.hoadon'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='MaKhachHang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_HoaDon_KhachHang', to='QLKS.khachhang'),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='MaNhanVien',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_HoaDon_NhanVien', to='QLKS.nhanvien'),
        ),
        migrations.CreateModel(
            name='Phong',
            fields=[
                ('SoPhong', models.IntegerField(primary_key=True, serialize=False)),
                ('TinhTrang', QLKS.models.NVarCharField(max_length=50)),
                ('HinhAnh', QLKS.models.NVarCharField(max_length=50)),
                ('MaLoai', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_Phong_LoaiPhong', to='QLKS.loaiphong')),
            ],
        ),
        migrations.AddField(
            model_name='dondatphong',
            name='SoPhong',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FK_DonDatPhong_Phong', to='QLKS.phong'),
        ),
    ]
