# Generated by Django 5.0.4 on 2024-05-22 15:24

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QLKS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dondatdichvu',
            name='NgayDat',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 22, 24, 17, 541310)),
        ),
        migrations.AlterField(
            model_name='dondatphong',
            name='NgayNhanPhong',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 22, 24, 17, 541310)),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='NgayXuat',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 22, 22, 24, 17, 541310)),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tentk', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('makh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_Account_KhachHang', to='QLKS.khachhang')),
                ('manv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FK_Account_NhanVien', to='QLKS.nhanvien')),
            ],
        ),
    ]
